// <auto-generated />
namespace OnlineShopping.DomainLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedcartupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcartupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "202012120827349_addedcartupdated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
